### ISSUE TITLE
Support angle brackets

### ISSUE THREAD

**Issue by lishine** [Pustelto/Bracketeer#35]
Would you please?

**Comment by Pustelto** [comment]
Hi @lishine do you mean `<` and `>`? For what language? They are not ordinary brackets, so support for them may be difficult. Can you provide any use case where do you need this?

Thanks.

**Comment by lishine** [comment]
Jsx
Like React etc.

**Comment by Pustelto** [comment]
And exact use case? You want to be able to select content between angle brackets or swap them? Selecting content make sense in some cases. I did a quick check and Prism.js have support for JSX, so it could be possible to add it. Need to do a proper investigation though.

**Comment by lishine** [comment]
Sorry to mislead you. The use case is typescript types in angle brackets such as useState<Type> 
Ability to select content inside these brackets and then to expand it to include the brackets.
Maybe swap brackets as well, I just don't remember if it is needed.
Inside ts and tsx files.
Actually probably this should be the responsibility of expand region/smart select features or extensions.

**Comment by Pustelto** [comment]
I see, yeah I could use that too 😄. Sounds like good idea so I will have a look on it. It will probably need more code to work properly. Since you actually need only selecting content, changing angle brackets to another one is not what you want and it would lead to invalid code which wouldn't be parsable by Prism and you couldn't swap the brackets anymore.

**Comment by Pustelto** [comment]
Done in #40. Works in ts and tsx files. Will be in next release.
