### ISSUE TITLE
Cannot quote text inside of PowerShell comment or JSON

### ISSUE THREAD

**Issue by atscripter** [Pustelto/Bracketeer#8]
I'm finding this extension ever-more useful but I did observe a little quirk with using quotes.

Demo:

![powershell](https://user-images.githubusercontent.com/36570016/54329030-75a43080-45e6-11e9-9f65-aab0aef191c7.gif)

![json](https://user-images.githubusercontent.com/36570016/54329034-789f2100-45e6-11e9-90f7-456671250925.gif)

**Comment by Pustelto** [comment]
HI @atscripter glad to hear you find this extension useful. And thanks for reporting the issue. I will try to dive in as soon as possible.

I'm using prism package to parse language tokens as VS Code does not provided any good solution out of the box. So not sure if the issue with comment can be fixed (as prism usually interpret it as comment). Not sure about the json, but will have a look. Get in touch with you as soon as I have a chance to look into this.

Thanks

**Comment by Pustelto** [comment]
@atscripter I have a quick look in the train during the weekend into this issue. Fixing the JSON issue should be fairly easy. Parsing the comment will be a bit harder and probably not implemented right away. Since Prism is evaluating it as a comment it does not detect brackets or quotes. I want to try to extract the content of the comment and parse it. Then I should be able to make it work in comments. But it will take some time and I don't have much of it to be honest, but I want to make it work. So have a patience 🙏 .

I will probably use this opportunity and refactor a bit to make it easily extensible for other languages (since I mainly use JS this extension works best there, but I want it to be universal, it should mostly works but there are some scenarios like the ones you discover where it does not work well).

**Comment by atscripter** [comment]
@Pustelto Thank you. On my part I will update you with any other issues I may encounter.

**Comment by Pustelto** [comment]
hi @atscripter, I have just released version 1.2.0, mainly internal changes but it fixes json problem. No fix for the comments yet, but I'm thinking about some workaround. If you do not mind. I will close this issue and open a new one targeted for comments only.

**Comment by atscripter** [comment]
@atscripter I tested quote selection on JSON and it works great, thank you!

You definitely may close this.

**Comment by Pustelto** [comment]
👍
